### PR TITLE
Add determined spawnpoints from MAD database to map

### PR DESCRIPTION
**Pull request by pkiel**
## Description
Adds back spawnpoints but only determined ones.
In a very simple way...

Warning:
This first push is setting all spawnpoint-types to 30 minutes spawns.
Did this because I don't know if MAD is detecting 60 minutes spawns correctly.
(In madmin it is incorrect!)

Help for this is welcome.

I didn't want to destroy the old RM code because who knows the future. So I left unused code in the class.

## How Has This Been Tested?

Locally on my server.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by na-ji** [comment]
Hello! Thanks for this feature! However, I get a an error when trying your PR:
```
[2019-03-02 21:52:09,896] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/home/naji/.local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/naji/.local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/naji/.local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/naji/.local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/naji/.local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/naji/www/pogo/OSM-Rocketmap/pogom/app.py", line 573, in raw_data
    swLat=swLat, swLng=swLng, neLat=neLat, neLng=neLng)
  File "/home/naji/www/pogo/OSM-Rocketmap/pogom/models.py", line 1352, in get_spawnpoints
    sp['earliest_unseen'] = int(int(sp['earliest_unseen'][:2])*60
ValueError: invalid literal for int() with base 10: '1:'
```
I tried with the latest version of MAD, do you want my `trs_spawn` table ?

**Comment by pkiel** [comment]
@na-ji Oh maybe you imported old spawns? Seem that the format ist different then XX:YY.
Using split(':') should fix it. Please try again.

**Comment by na-ji** [comment]
Now it is working. BTW do you know what those values means? 
image

**Comment by pkiel** [comment]
Thanks for testing.
This is the old RM style. From `MINUTE:SECOND` to `MINUTE:SECOND`.

**Comment by JimBim89** [comment]
Thanks for this, works as expected.

**Pull request merged**
